// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:notely/features/note/models/note_model.dart';
import 'package:notely/features/profile/models/user_profile_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(NoteHiveModelAdapter());
    registerAdapter(UserProfileAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(NoteHiveModelAdapter());
    registerAdapter(UserProfileAdapter());
  }
}
